In [50]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [51]:
import os
os.chdir('/Users/sebas/projects/metabolomics')

In [52]:
import dill

In [53]:
data_folder= '/Users/sebas/projects/data/'
uniformed_molecule_pairs_test_path= data_folder +'uniformed_molecule_pairs_test.pkl'


In [54]:
with open(uniformed_molecule_pairs_test_path, 'rb') as file:
            dataset = dill.load(file)
molecule_pairs= dataset['uniformed_molecule_pairs_test']

In [11]:
spectrums= molecule_pairs.spectrums

In [21]:
index_spec=10000
print(spectrums[index_spec].params)
print(spectrums[index_spec].params['smiles'])

{'libraryquality': 1, 'charge': [1], 'pepmass': [229.0972], 'ionmode': 'Positive', 'name': ' Ozagrel\n M+H', 'inchi': 'N/A', 'smiles': 'C1=CC(=CC=C1CN2C=CN=C2)C=CC(=O)O', 'organism': 'nist', 'spectrumid': 'abcd'}
C1=CC(=CC=C1CN2C=CN=C2)C=CC(=O)O


In [22]:
spectrums[index_spec].intensity

array([ 57.34,  71.63,  14.79,  21.88,  96.2 ,  15.08,  16.38,  99.2 ,
       999.  ,  38.96,  84.12, 412.09], dtype=float32)

In [23]:
spectrums[index_spec].mz

array([ 55.019,  68.997,  77.039,  79.054,  91.054,  93.07 , 103.054,
       105.069, 115.053, 119.048, 133.063, 161.058])

In [77]:
spectrums[index_spec].params

{'libraryquality': 1,
 'charge': [1],
 'pepmass': [229.0972],
 'ionmode': 'Positive',
 'name': ' Ozagrel\n M+H',
 'inchi': 'N/A',
 'smiles': 'C1=CC(=CC=C1CN2C=CN=C2)C=CC(=O)O',
 'organism': 'nist',
 'spectrumid': 'abcd'}

In [78]:
for intensity, mz in zip(spectrums[index_spec].intensity,spectrums[index_spec].mz):
    print(f'MZ peak at: {mz}, intensity: {intensity}')

MZ peak at: 55.019, intensity: 57.34000015258789
MZ peak at: 68.997, intensity: 71.62999725341797
MZ peak at: 77.039, intensity: 14.789999961853027
MZ peak at: 79.054, intensity: 21.8799991607666
MZ peak at: 91.054, intensity: 96.19999694824219
MZ peak at: 93.07, intensity: 15.079999923706055
MZ peak at: 103.054, intensity: 16.3799991607666
MZ peak at: 105.069, intensity: 99.19999694824219
MZ peak at: 115.053, intensity: 999.0
MZ peak at: 119.048, intensity: 38.959999084472656
MZ peak at: 133.063, intensity: 84.12000274658203
MZ peak at: 161.058, intensity: 412.0899963378906


In [62]:
print(molecule_pairs[180000])

Molecular pair with similarity: 0.9309090909090909 for smiles_0: C1C(C(C(C(O1)OC2C(C(OC2OC3=C(OC4=CC(=CC(=C4C3=O)O)O)C5=CC(=C(C=C5)O)O)CO)O)O)O)O and smiles_1: C1=CC(=C(C=C1C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)OC4C(C(C(C(O4)CO)O)O)O)O)OC5C(C(C(C(O5)CO)O)O)O


In [73]:
molecule_pairs[180000].spectrum_object_0.params

{'libraryquality': 1,
 'charge': [1],
 'pepmass': [567.1344],
 'ionmode': 'Positive',
 'name': ' Polifolioside\n M+H',
 'inchi': 'N/A',
 'smiles': 'C1C(C(C(C(O1)OC2C(C(OC2OC3=C(OC4=CC(=CC(=C4C3=O)O)O)C5=CC(=C(C=C5)O)O)CO)O)O)O)O',
 'organism': 'nist',
 'spectrumid': 'abcd'}

In [74]:
molecule_pairs[180000].spectrum_object_1.params

{'pepmass': (627.57, None),
 'charge': [1],
 'mslevel': '2',
 'source_instrument': 'ESI-QQQ',
 'filename': 'massbank-gnps.mgf',
 'seq': '*..*',
 'ionmode': 'Positive',
 'organism': 'MASSBANK',
 'name': "Massbank:PS121901 Quercetin-3,4'-O-di-beta-glucopyranoside|Quercetin 3,4'-diglucoside|Que 3,4'-di-Glc M+H",
 'pi': 'Massbank',
 'datacollector': 'Massbank',
 'smiles': 'C1=CC(=C(C=C1C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)OC4C(C(C(C(O4)CO)O)O)O)O)OC5C(C(C(C(O5)CO)O)O)O',
 'inchi': '1S/C27H30O17/c28-6-14-17(33)20(36)22(38)26(42-14)41-12-2-1-8(3-10(12)31)24-25(19(35)16-11(32)4-9(30)5-13(16)40-24)44-27-23(39)21(37)18(34)15(7-29)43-27/h1-5,14-15,17-18,20-23,26-34,36-39H,6-7H2',
 'inchiaux': 'N/A',
 'pubmed': 'N/A',
 'submituser': 'mwang87',
 'libraryquality': '3',
 'spectrumid': 'CCMSLIB00005759814',
 'scans': '34263'}

In [84]:
import numpy as np
intensity = np.array(molecule_pairs[180000].spectrum_object_1.intensity)/np.sum(molecule_pairs[180000].spectrum_object_1.intensity)
mz_values= molecule_pairs[180000].spectrum_object_1.mz

for inten, mz in zip(intensity,mz_values):
    print(f'MZ peak at: {mz}, intensity: {inten}')

MZ peak at: 464.0, intensity: 0.032549899071455
MZ peak at: 465.0, intensity: 0.1180637776851654
MZ peak at: 466.0, intensity: 0.04817274585366249
MZ peak at: 626.0, intensity: 0.12372517585754395
MZ peak at: 627.0, intensity: 0.3087349534034729
MZ peak at: 628.0, intensity: 0.3293459415435791
MZ peak at: 629.0, intensity: 0.03940752148628235


In [75]:
molecule_pairs[180000].spectrum_object_0.mz

array([ 57.0333,  73.0281,  85.0282,  97.0281, 115.0387, 125.9927,
       126.1046, 133.0494, 287.0547, 288.0581, 289.0603, 303.0496,
       315.0495, 322.8683, 327.0502, 345.06  , 369.06  , 381.062 ,
       399.0704, 417.0815, 435.0916, 489.05  ])

In [72]:
molecule_pairs[180000].spectrum_object_1.mz

array([464., 465., 466., 626., 627., 628., 629.])